name=input("이름은?")
print("영어,수학,국어 점수를 입력하세요:")
english=int(input())
math=int(input())
korean=int(input())
print(name,"님의 과목별 점수입니다")
print("영어 ",english)
print("수학 ",math)
print("국어 ",korean)
